"""PortSwigger-style SQL injection learning track (8 hands-on labs)."""

TRACK_LABS = [
    {
        "number": 1,
        "slug": "track-01-auth-bypass",
        "title": "SQL injection in a login bypass",
        "subtitle": "Manipulate a WHERE clause to log in without valid credentials",
        "sqli_type": "auth-bypass",
        "difficulty": "apprentice",
        "points": 100,
        "flag": "FLAG{auth_bypass_admin}",
        "portswigger_topic": "Authentication bypass",
    },
    {
        "number": 2,
        "slug": "track-02-error-based",
        "title": "SQL injection error-based extraction",
        "subtitle": "Trigger verbose errors to leak query structure and data",
        "sqli_type": "error-based",
        "difficulty": "apprentice",
        "points": 110,
        "flag": "FLAG{error_based_alpha}",
        "portswigger_topic": "Error-based SQLi",
    },
    {
        "number": 3,
        "slug": "track-03-union-columns",
        "title": "UNION attack — finding columns",
        "subtitle": "Determine the correct number of columns for a UNION SELECT",
        "sqli_type": "union-based",
        "difficulty": "practitioner",
        "points": 120,
        "flag": "FLAG{union_product_leak}",
        "portswigger_topic": "UNION — column count",
    },
    {
        "number": 4,
        "slug": "track-04-union-extract",
        "title": "UNION attack — retrieving data",
        "subtitle": "Extract sensitive values from other tables via UNION",
        "sqli_type": "union-based",
        "difficulty": "practitioner",
        "points": 130,
        "flag": "FLAG{union_shadow}",
        "portswigger_topic": "UNION — data extraction",
    },
    {
        "number": 5,
        "slug": "track-05-boolean-blind",
        "title": "Blind SQLi — conditional responses",
        "subtitle": "Infer secrets when the app only returns true/false differences",
        "sqli_type": "boolean-blind",
        "difficulty": "practitioner",
        "points": 140,
        "flag": "FLAG{boolean_blind_bob}",
        "portswigger_topic": "Boolean-based blind",
    },
    {
        "number": 6,
        "slug": "track-06-time-blind",
        "title": "Blind SQLi — time delays",
        "subtitle": "Use measurable delays when no visible output changes",
        "sqli_type": "time-based",
        "difficulty": "expert",
        "points": 150,
        "flag": "FLAG{time_based_carol}",
        "portswigger_topic": "Time-based blind",
    },
    {
        "number": 7,
        "slug": "track-07-second-order",
        "title": "Second-order SQL injection",
        "subtitle": "Store a payload safely, then trigger it in a later query",
        "sqli_type": "second-order",
        "difficulty": "expert",
        "points": 160,
        "flag": "FLAG{second_order_stored}",
        "portswigger_topic": "Second-order SQLi",
    },
    {
        "number": 8,
        "slug": "track-08-stacked",
        "title": "Stacked queries (advanced)",
        "subtitle": "Chain multiple statements where the driver allows it",
        "sqli_type": "stacked-queries",
        "difficulty": "expert",
        "points": 170,
        "flag": "FLAG{stacked_schema_peek}",
        "portswigger_topic": "Stacked queries",
    },
]


def get_track_slugs() -> list[str]:
    return [lab["slug"] for lab in TRACK_LABS]
